# Generated by Django 4.0.6 on 2022-07-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=20)),
                ('ResidencyName', models.CharField(max_length=20)),
                ('FlatType', models.CharField(max_length=20)),
                ('FlatNomber', models.IntegerField()),
                ('FlowrNomber', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
